# -*- coding:utf-8 -*-

"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%^jkrk$04drpx$z1=i^sn^4_(ogi=(v^m-5n#+dpibf2uz!^vh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [ # 上下文处理器
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.views.global_setting',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'USER': 'root',
        'PASSWORD': 'destination',
    }
    # 'default' : {
    #     'ENGINE' : 'django.db.backends.mysql',
    #     'NAME' : 'blogdb', # 数据库名称
    #     'USER' : '',
    #     'PASSWORD' : '',
    #     'HOST' : '',
    #     'PORT' : '',
    # }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

#自定义用户model
AUTH_USER_MODEL = 'blog.User'

#添加静态文件目录到工程中
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

#网站的基本信息配置(全局设置)
SITE_NAME = '唐嘉良的个人博客'
SITE_DESC = 'python学习博客'
WEBO_SINA = ''
WEBO_TENCENT = ''
PRO_RSS = ''
PRO_EMAIL = 'phx108@sina.com'

# 媒体文件路径
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')


#自定义日志输出信息
LOGGING = {
    'version' : 1,
    'disable_existing_loggers' : True,
    'formatters' : {
            'standard' : {
            'format' : '%(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s] - %(message)s',
        }
    } ,
    'filters' : {
    } ,
    'handlers' : {
        'mail_admins' : {
            'level' : 'ERROR',
            'class' : 'django.utils.log.AdminEmailHandler',
            'include_html' : True,
        },
        'default' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : 'log/all.log', #  	日志输出文件
            'maxBytes': 1024*1024*5, 	#	文件大小
            'backupCount' : 5,
            'formatter' : 'standard' ,
        },
        'error' : {
            'level' : 'ERROR',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : 'log/error.log' ,
            'maxBytes' : 1024*1024**5,
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'console' : {
            'level' : 'DEBUG',
            'class' : 'logging.StreamHandler',
            'formatter' : 'standard',
        } ,
        'request_handler' : {
            'level' : 'DEBUG',
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : 'log/script.log',
            'maxBytes' : '1024*1024*5',
            'backupCount' : 5,
            'formatter' : 'standard',
        },
        'scripts_handler' : {
            'level' : 'DEBUG' ,
            'class' : 'logging.handlers.RotatingFileHandler',
            'filename' : 'log/script.log' ,
            'maxBytes' : 1024*1024*5 ,
            'backupCount' : 5,
            'formatter' : 'standard' ,
        }
    } ,
    'loggers' : {
        'django' : {
            'handlers' : ['default', 'console'],
            'propagate' : False,
        } ,
        'django.requst' : {
            'handlers' : ['request_handler'],
            'level' : 'DEBUG',
            'propagate' : False ,
        },
        'scripts' : {
            'handlers' : ['scripts_handler'] ,
            'level' : 'INFO' ,
            'propagate' : False
        },
        'blog.views' : {
            'handlers' : ['default', 'error'],
            'level' : 'DEBUG' ,
            'propagate' : True,
        },
    }

}